trigger:
- master

pool:
  vmImage: 'ubuntu-latest' # other options: 'macOS-10.13', 'vs2017-win2016'

steps:
- task: Gradle@2
  inputs:
    gradleWrapperFile: '$(system.defaultWorkingDirectory)/gradlew' 
    tasks: 'clean test --info'
    gradleOptions: '-Xmx1024m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'